name: Reusable Salesforce Deploy

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      from_ref:
        required: true
        type: string
      to_ref:
        required: true
        type: string
      test_level:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Install PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0/pmd-bin-7.0.0.zip
          unzip pmd-bin-7.0.0.zip -d pmd
          echo "$(pwd)/pmd/pmd-bin-7.0.0/bin" >> $GITHUB_PATH

      - name: Run PMD
        run: |
          pmd check -d force-app -R ruleset.xml -f text

      - name: Run Deployment
        run: |
          echo "Deploying from ${{ inputs.from_ref }} to ${{ inputs.to_ref }} on ${{ inputs.target }}"
          sfdx force:source:deploy \
            -p force-app \
            -u "${{ inputs.target }}" \
            -l ${{ inputs.test_level }}
